In [5]:
import tensorflow.keras.datasets as datasets
import matplotlib.pyplot as plt
import numpy as np
from skimage.feature import hog
import linear_models.softmaxreg as softmaxreg
import umap
import matplotlib.pyplot as plt
import numpy as np
import metrics.metrics as metrics

In [6]:
def getSample(n_rows, n_cols, data):
    size = 28
    image = np.ones((n_rows*size, n_cols*size), dtype = np.uint8)*255
    n = n_rows * n_cols
    idx = np.random.randint(data.shape[0], size = n)
    
    i = 0
    for r in np.arange(n_rows) :
            for c in np.arange(n_cols) :
                image[r * size:(r + 1) * size, c * size : (c + 1) * size] = data[idx[i], : , : ]
                i = i + 1
    
    return image

In [7]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()
print ('{} {}'.format(x_train.shape, x_train.dtype))
print ('{} {}'.format(x_test.shape, x_train.dtype))
digit = x_train[0,:,:]
print(digit.shape)

(60000, 28, 28) uint8
(10000, 28, 28) uint8
(28, 28)


In [8]:
SM = softmaxreg.SoftmaxReg(10)

In [ ]:
#DATA NORMALIZATION (tira error por alguna division por 0)
# mu = np.mean(x_train, axis=0)
# dst = np.std(x_train, axis=0)
# x_train = (x_train - mu) / dst
# x_test = (x_test - mu ) / dst

In [13]:
x_train_d_728 = x_train.reshape(60000,-1)
coeff = SM.fit(x_train_d_728, y_train)

it 0 acc 0.10318333333333334
it 10 acc 0.66325
it 20 acc 0.8716833333333334
it 30 acc 0.8412166666666666
it 40 acc 0.7999833333333334
it 50 acc 0.8168166666666666
it 60 acc 0.8924
it 70 acc 0.7296833333333334
it 80 acc 0.7715833333333333
it 90 acc 0.89445
it 100 acc 0.9032333333333333
it 110 acc 0.8992
it 120 acc 0.788
it 130 acc 0.9051666666666667
it 140 acc 0.9039
it 150 acc 0.8073333333333333
it 160 acc 0.8804
it 170 acc 0.8849
it 180 acc 0.9113166666666667
it 190 acc 0.9142666666666667


In [14]:
x_test_d_728 = x_test.reshape(10000,-1)
y_pred = SM.predict(x_test_d_728)

In [15]:
acc = metrics.multiclass_accuracy(y_test, y_pred)
print(f"Accuracy: {acc}")

Accuracy: 0.797


In [16]:
cm = metrics.confusion_matrix(y_test, y_pred, 10)
print(f'Confusion Matrix\n{cm}')

Confusion Matrix
[[941   0   0   1   0   1   6   4  27   0]
 [  0 941   2   0   0   0   2   2 188   0]
 [  8   8 800   5   6   0  13  13 176   3]
 [  5   1   9 655   1   7   2  16 312   2]
 [  1   0   1   1 862   0   9   3  95  10]
 [ 10   2   2  14  10 388  12  10 441   3]
 [ 15   2   0   1  15   5 845   3  72   0]
 [  1   4  11   4   7   0   0 954  37  10]
 [  2   0   0   1   4   1   2   2 962   0]
 [  6   3   0   2  36   1   0  61 278 622]]
